name = "atomic_teal_snail-6dba"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "atomic_teal_snail-6dba_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "atomic_teal_snail-6dba.wasm"
command = "npm run build:release"
